language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libsdl1.2-dev
      - libsdl-ttf2.0-dev
      - libsdl-image1.2-dev

script:
  - ./autogen.sh
  - ./configure --disable-curses --enable-sdl
  - make
