MKPATH=../../mk/
include $(MKPATH)buildsys.mk

CONFIG = \
       font-gcu.prf font-sdl.prf font-sdl2.prf font-win.prf font-x11.prf \
       font.prf font-tng.prf \
       keys-gcu.prf message.prf pref.prf user.prf sound.prf \
       class.prf presets.prf race.prf

PACKAGE = customize
